[package]
name = "java_class_manipulation"
version = "0.1.0"
authors = ["Kevin Moonen <dragonrider7225@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.1.2"
extended_io = { git = "https://github.com/dragonrider7225/extended_io.git" }
clap = "2.33.0"
num_enum = "0.5.0"
