[package]
name = "java_class_manipulation"
version = "0.1.0"
authors = ["Kevin Moonen <dragonrider7225@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.0.0"
extended_io = { git = "https://github.com/dragonrider7225/extended_io.git" }
